{% set name = "ecFlow" %}
{% set version = "5.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-Source.tar.gz
  url: https://confluence.ecmwf.int/download/attachments/8650755/{{ name }}-{{ version }}-Source.tar.gz
  sha256: cf5f3588c8f4b7e3785eb25666533710fa2c0b7f0407cb455f84b4ac30a83a3e

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
  host:
    - python
    - boost
    - qt
    - xorg-libxfixes  # [linux]
  run:
    - python
    - qt

test:
  commands:
    - conda inspect linkages -p $PREFIX ecflow
    - conda inspect objects -p $PREFIX ecflow  # [osx]
    - ecflow_client --help
    - ecflow_server --help
    - ecflow_standalone --help
    - ecflow_ui_log -h

about:
  home: https://confluence.ecmwf.int/display/ECFLOW
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecFlow

extra:
  recipe-maintainers:
    - dtip
    - avi369
    - iainrussell
    - StephanSiemen
