{% set name = "ecFlow" %}
{% set version = "5.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-Source.tar.gz
  url: https://confluence.ecmwf.int/download/attachments/8650755/{{ name }}-{{ version }}-Source.tar.gz
  sha256: bc628556f8458c269a309e4c3b8d5a807fae7dfd415e27416fe9a3f544f88951


build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
  host:
    - python
    - boost
    - qt-main
    - xorg-libxfixes  # [linux]
  run:
    - python
    - qt-main
    - boost

test:
  commands:
    - ecflow_client --help
    - ecflow_server --help
    - ecflow_standalone -v

about:
  home: https://confluence.ecmwf.int/display/ECFLOW
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecFlow

extra:
  recipe-maintainers:
    - dtip
    - avi369
    - iainrussell
    - StephanSiemen
