{% set name = "ecFlow" %}
{% set version = "5.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-Source.tar.gz
  url: https://confluence.ecmwf.int/download/attachments/8650755/{{ name }}-{{ version }}-Source.tar.gz
  sha256: 666f804473e0bdc63f51e0b74531217c74f6e6ed40a33c11f7d2916918489741

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - libboost-python-devel
    - qt-main
    - xorg-libxfixes  # [linux]
    - zlib  # [linux]
    - libxcrypt  # [linux]
    - libgl-devel                    # [linux]
  run:
    - python
    - qt-main
    - libboost-python-devel
    - zlib  # [linux]
    - libxcrypt  # [linux]

test:
  commands:
    - ecflow_client --help
    - ecflow_server --help
    - ecflow_standalone -v

about:
  home: https://ecflow.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecFlow

extra:
  recipe-maintainers:
    - marcosbento
    - dtip
    - avi369
    - iainrussell
    - StephanSiemen
