{% set name = "ecFlow" %}
{% set version = "5.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-Source.tar.gz
  url: https://confluence.ecmwf.int/download/attachments/8650755/{{ name }}-{{ version }}-Source.tar.gz
  sha256: 01223d93cc31d976fd955c37a03d4a145cfd27a81db86b5b94878275e94e4ec5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - libboost-python-devel
    - qt-main
    - xorg-libxfixes  # [linux]
    - zlib  # [linux]
    - libxcrypt  # [linux]
    - libgl-devel                    # [linux]
  run:
    - python
    - qt-main
    - libboost-python-devel
    - zlib  # [linux]
    - libxcrypt  # [linux]

test:
  commands:
    - ecflow_client --help
    - ecflow_server --help
    - ecflow_standalone -v

about:
  home: https://ecflow.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecFlow

extra:
  recipe-maintainers:
    - marcosbento
    - dtip
    - avi369
    - iainrussell
    - StephanSiemen
