{% set name = "ecFlow" %}
{% set version = "5.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-Source.tar.gz
  url: https://confluence.ecmwf.int/download/attachments/8650755/{{ name }}-{{ version }}-Source.tar.gz
  sha256: d18acd93d42f8ccdff9fc3f07d5a9667ff4861e53c40af35de36ce77ab100bb8
  patches:
    - 0001-Add-missing-includes-ECFLOW-1881.patch
    - 0002-Correct-UDP-test-linkage-with-Boost-dynamic-librarie.patch
    - 0003-Use-MSG_NOSIGNAL-only-when-defined-ECFLOW-1881.patch
    - 0004-Correct-typo-in-comment-ECFLOW-1881.patch
    - 0005-Use-MSG_NOSIGNAL-only-when-defined-ECFLOW-1881.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
  host:
    - python
    - boost
    - qt-main
    - xorg-libxfixes  # [linux]
  run:
    - python
    - qt-main
    - boost

test:
  commands:
    - ecflow_client --help
    - ecflow_server --help
    - ecflow_standalone -v

about:
  home: https://ecflow.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecFlow

extra:
  recipe-maintainers:
    - dtip
    - avi369
    - iainrussell
    - StephanSiemen
